---
githubRepo: https://github.com/trustoverip/hxwg.wiki.git
googleDoc: https://docs.google.com/document/d/1fZByfuSOwszDRkE7ARQLeElSYmVznoOyJK4sxRvJpyM/export?format=html
# TEv2 Curated Text Header
term: curated-text
termType: concept
isa:
glossaryText: a text that documents a [concept](@) or other [knowledge artifact](@) of a specific [community](@) or other [party](@), and is located within a [scope](@) that is owned by that [community](@)/[party](@).
synonymOf:
groupTags:
formPhrases: curated-text{ss}, ctext{ss}
# Curation status
status: proposed
created: 2022-06-02
updated: 2022-08-04
# Origins/Acknowledgements
contributors: RieksJ
attribution: "[eSSIF-Lab](https://essif-lab.github.io/framework)"
originalLicense: "[CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)"
